export const DEFAULT_RENTER_SEARCH_RADIUS_KM = 15;
export const DEFAULT_RENTER_SEARCH_RADIUS = String(DEFAULT_RENTER_SEARCH_RADIUS_KM);
export const MIN_RENTER_SEARCH_RADIUS_KM = 0.5;
export const MAX_RENTER_SEARCH_RADIUS_KM = 100;
export const MAX_RENTER_SEARCH_BEDROOMS = 20;
export const MAX_RENTER_SEARCH_RENT_BDT = 10_000_000;
