create table if not exists private.phone_reveal_events (
  id bigint generated by default as identity primary key,
  viewer_id uuid not null references public.profiles(id) on delete cascade,
  property_id uuid not null references public.properties(id) on delete cascade,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  revealed_at timestamptz not null default now()
);

create index if not exists phone_reveal_events_viewer_recent_idx
  on private.phone_reveal_events (viewer_id, revealed_at desc);

create or replace function public.reveal_property_owner_phone(property_uuid uuid)
returns table(phone text, owner_phone_verified_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  viewer uuid := (select auth.uid());
  viewer_verified_at timestamptz;
  listing record;
  owner_phone text;
  recent_reveals integer;
begin
  if viewer is null then
    raise exception 'Sign in required';
  end if;

  select p.phone_verified_at
    into viewer_verified_at
  from public.profiles p
  where p.id = viewer;

  if viewer_verified_at is null then
    raise exception 'Phone verification required';
  end if;

  select pr.owner_id, owner.phone_verified_at
    into listing
  from public.properties pr
  join public.profiles owner on owner.id = pr.owner_id
  where pr.id = property_uuid
    and pr.status = 'available'::public.listing_status
    and pr.published_at is not null
    and (pr.expires_at is null or pr.expires_at > now());

  if not found then
    raise exception 'Property is not currently available';
  end if;

  if listing.owner_id = viewer then
    raise exception 'Owners cannot reveal their own contact through this endpoint';
  end if;

  if listing.phone_verified_at is null then
    raise exception 'Owner phone is not verified';
  end if;

  select count(*)::integer
    into recent_reveals
  from private.phone_reveal_events e
  where e.viewer_id = viewer
    and e.revealed_at > now() - interval '1 hour';

  if recent_reveals >= 20 then
    raise exception 'Phone reveal rate limit reached';
  end if;

  select u.phone
    into owner_phone
  from auth.users u
  where u.id = listing.owner_id;

  if owner_phone is null or btrim(owner_phone) = '' then
    raise exception 'Owner phone is unavailable';
  end if;

  insert into private.phone_reveal_events (viewer_id, property_id, owner_id)
  values (viewer, property_uuid, listing.owner_id);

  return query select owner_phone, listing.phone_verified_at;
end;
$$;

revoke all on function public.reveal_property_owner_phone(uuid) from public;
grant execute on function public.reveal_property_owner_phone(uuid) to authenticated;
